import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { planId, gateway, userId } = await req.json();

    if (!planId || !gateway || !userId) {
      throw new Error("Missing required fields: planId, gateway, userId");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get plan details
    const { data: plan, error: planError } = await supabase
      .from("subscription_plans")
      .select("*")
      .eq("id", planId)
      .single();

    if (planError || !plan) {
      throw new Error("Plan not found");
    }

    // Check if user is admin (free access)
    const { data: roles } = await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", userId);

    const isAdmin = roles?.some((r: any) => r.role === "admin");

    if (isAdmin) {
      // Admin gets free access
      await supabase.from("profiles").update({
        subscription_plan_id: planId,
        subscription_status: "active",
        subscription_expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      }).eq("user_id", userId);

      await supabase.from("payments").insert({
        user_id: userId,
        plan_id: planId,
        amount: 0,
        gateway: "admin_free",
        status: "success",
        metadata: { note: "Admin free access" },
      });

      return new Response(JSON.stringify({ success: true, message: "Admin free access granted" }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // For each gateway, generate payment URL
    // In production, each gateway would have its own API integration
    const gatewayConfigs: Record<string, { envKey: string; name: string }> = {
      yookassa: { envKey: "YOOKASSA_SECRET_KEY", name: "ЮКасса" },
      robokassa: { envKey: "ROBOKASSA_SECRET_KEY", name: "Робокасса" },
      cloudpayments: { envKey: "CLOUDPAYMENTS_SECRET_KEY", name: "CloudPayments" },
      unitpay: { envKey: "UNITPAY_SECRET_KEY", name: "UnitPay" },
      yoomoney: { envKey: "YOOMONEY_SECRET_KEY", name: "ЮMoney" },
      payanyway: { envKey: "PAYANYWAY_SECRET_KEY", name: "PayAnyway" },
      yandexpay: { envKey: "YANDEXPAY_SECRET_KEY", name: "Yandex Pay" },
      leadpay: { envKey: "LEADPAY_SECRET_KEY", name: "LeadPay" },
    };

    const config = gatewayConfigs[gateway];
    if (!config) {
      throw new Error(`Unknown payment gateway: ${gateway}`);
    }

    const secretKey = Deno.env.get(config.envKey);

    // Create pending payment record
    const { data: payment } = await supabase.from("payments").insert({
      user_id: userId,
      plan_id: planId,
      amount: plan.price_monthly,
      gateway,
      status: "pending",
    }).select().single();

    if (!secretKey) {
      // Gateway not configured yet — return info
      return new Response(JSON.stringify({
        success: false,
        message: `Платёжная система ${config.name} ещё не настроена. Обратитесь к администратору.`,
      }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Here you would integrate with each payment gateway's API
    // For now, return a placeholder response
    return new Response(JSON.stringify({
      success: true,
      paymentId: payment?.id,
      message: `Переход к оплате через ${config.name}...`,
      // paymentUrl would be generated by the actual gateway API
    }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error: any) {
    console.error("Payment error:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
